const withMT = require("@material-tailwind/react/utils/withMT");
 
const toColors = (colorCode) => {
  return {
    50:  colorCode,
    100: colorCode,
    200: colorCode,
    300: colorCode,
    400: colorCode,
    500: colorCode,
    600: colorCode,
    700: colorCode,
    800: colorCode,
    900: colorCode,
  };
}
module.exports = withMT({
  content: ["./pages/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {

      colors: {
        "kuzuha": toColors("#ACA7BB" ),
        "salome-hyakumantenbara": toColors("#CD3796" ),
        "kanae": toColors("#ABD3D8" ),
        "mito-tsukino": toColors("#E43F3B" ),
        "toya-kenmochi": toColors("#A590AF" ),
        "sara-hoshikawa": toColors("#FAB80D" ),
        "minato-fuwa": toColors("#BF69F4" ),
        "luca-kaneshiro": toColors("#D4AF37" ),
        "shu-yamino": toColors("#A660A7" ),
        "lize-helesta": toColors("#42FFFF" ),
        "saku-sasaki": toColors("#EF9AAF" ),
        "kaede-higuchi": toColors("#FBAF71" ),
        "kizuku-yashiro": toColors("#B6C6F2" ),
        "ars-almal": toColors("#7FD6E2" ),
        "hayato-kagami": toColors("#B9ADB9" ),
        "yuika-shiina": toColors("#F1C8DE" ),
        "lauren-iroas": toColors("#C10E49" ),
        "ibrahim": toColors("#7CA1F0" ),
        "himawari-honma": toColors("#FBE340" ),
        "chima-machita": toColors("#80C8EF" ),
        "kokoro-amamiya": toColors("#C5EDFF" ),
        "furen-e-lustario": toColors("#EC1D2F" ),
        "akina-saegusa": toColors("#F03C32" ),
        "haru-kaida": toColors("#4DD7E3" ),
        "elu": toColors("#E2364F" ),
        "nui-sociere": toColors("#D24E5F" ),
        "ratna-petit": toColors("#F36C21" ),
        "chigusa-nishizono": toColors("#3A8FB7" ),
        "debidebi-debiru": toColors("#444C7D" ),
        "kana-sukoya": toColors("#FF2FA2" ),
        "mikoto-rindou": toColors("#745BFF" ),
        "sango-suo": toColors("#EF8468" ),
        "sister-claire": toColors("#DFC6A8" ),
        "rena-yorumi": toColors("#F7265A" ),
        "meloco-kyoran": toColors("#A09BD8" ),
        "sonny-brisko": toColors("#FFF321" ),
        "elira-pendora": toColors("#95C8D8" ),
        "makaino-ririmu": toColors("#EF6F94" ),
        "chaika-hanabatake": toColors("#40CF84" ),
        "rion-takamiya": toColors("#CC3D7B" ),
        "hibari-watarai": toColors("#192332" ),
        "meme-mashiro": toColors("#1E2232" ),
        "gwelu-os-gar": toColors("#F04B2D" ),
        "rosemi-lovelock": toColors("#DC3753" ),
        "belmond-banderas": toColors("#683D46" ),
        "leos-vincent": toColors("#234A87" ),
        "fuyuki-hakase": toColors("#EEFFFF" ),
        "kei-nagao": toColors("#625DA1" ),
        "ex-albio": toColors("#5C9BBC" ),
        "maria-marionette": toColors("#E55A9B" ),
        "lain-paterson": toColors("#F74848" ),
        "kou-uzuki": toColors("#F9E97A" ),
        "akira-shikinagi": toColors("#235AAA" ),
        "levi-elipha": toColors("#FF5A00" ),
        "tojiro-genzuki": toColors("#B43246" ),
        "kakeru-yumeoi": toColors("#AC324B" ),
        "riri-yuhi": toColors("#BFFFFF" ),
        "dola": toColors("#A83E4A" ),
        "gaku-fushimi": toColors("#FFCB5B" ),
        "oliver-evans": toColors("#BCC37E" ),
        "kazaki-morinaka": toColors("#C8F39A" ),
        "yang-nari": toColors("#FAD1D6" ),
        "masaru-suzuki": toColors("#7B788A" ),
        "sophia-valentine": toColors("#C8C3DC" ),
        "mao-matsukai": toColors("#C93965" ),
        "hisui-kitakoji": toColors("#38B48B" ),
        "seraph-dazzlegarden": toColors("#DC3C41" ),
        "toru-koshimizu": toColors("#CDA5FF" ),
        "rou-koyanagi": toColors("#5A5FAA" ),
        "shiba-kuroi": toColors("#585C82" ),
        "nei-ponto": toColors("#5A7DFF" ),
        "sho-hoshirube": toColors("#A58CDC" ),
        "ritsuki-sakura": toColors("#C57FC7" ),
        "mana-hibachi": toColors("#64C8F0" ),
        "kanato-fura": toColors("#F0F0F5" ),
        "ruri-shioriha": toColors("#2887FF" ),
        "shoichi-kanda": toColors("#F4D35B" ),
        "sou-hayase": toColors("#AA7BE8" ),
        "nozomi-ishigami": toColors("#E6325F" ),
        "fumi": toColors("#F4E49D" ),
        "kaisei": toColors("#0C6F72" ),
        "karuta-yamagami": toColors("#384B5A" ),
        "luis-cammy": toColors("#E86A74" ),
        "akari-shishido": toColors("#FFD728" ),
        "natsume-kurusu": toColors("#8AD1EF" ),
        "yotsuha-umise": toColors("#FFE632" ),
        "eli-conifer": toColors("#DAFFF9" ),
        "haruka-onomachi": toColors("#FF336E" ),
        "rika-igarashi": toColors("#FF8C3C" ),
        "ver-vermillion": toColors("#D5345E" ),
        "ness-sakaki": toColors("#C2AAE6" ),
        "emma-august": toColors("#B32F51" ),
        "kagetsu-murakumo": toColors("#6EB487" ),
        "seffyna": toColors("#C92235" ),
        "rai-inami": toColors("#DCFF50" ),
        "rito-usami": toColors("#FAC31E" ),
        "meruto-kuramochi": toColors("#EB4682" ),
        "vezalius-bandage": toColors("#C34196" ),
        "roco-kaburaki": toColors("#198CAA" ),
        "wen-akagi": toColors("#FF8C9B" ),
        "min-suha": toColors("#5AC8FF" ),
        "hajime-shibuya": toColors("#D7FAD7" ),
        "yusei-kitami": toColors("#FF6E1E" ),
        "kyoko-todoroki": toColors("#F8A69A" ),
        "milan-kestrel": toColors("#2C35BD" ),
        "muyu-amagase": toColors("#FA5578" ),
        "rine-yaguruma": toColors("#FEECD8" ),
        "lee-roha": toColors("#EC399B" ),
        "ha-yun": toColors("#B14D4D" ),
        "toto-tachitsute": toColors("#C31E5A" ),
        "klara-charmwood": toColors("#DFCDBF" ),
        "na-sera": toColors("#FEECF3" ),
        "oh-jiyu": toColors("#F1F4F4" ),
        "ryu-hari": toColors("#96CEEB" ),
        "hex-haywire": toColors("#007199" ),
      }
    },
  },
  plugins: [],
});
